# Generated by Django 4.2.23 on 2025-07-11 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VotingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='closed', max_length=10)),
                ('members', models.ManyToManyField(blank=True, related_name='voting_events', to='ballot.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ballot.votingevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vote_type', models.CharField(choices=[('simple', 'Simple Vote (Agree/Disagree/Abstain)'), ('short_text', 'Short Text Input'), ('radio', 'Radio Buttons')], max_length=20)),
                ('type_specific_data', models.JSONField(blank=True, default=dict)),
                ('voting_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ballot.votingevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ballot.member')),
                ('voting_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ballot.votingevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('voting_event', 'member')},
            },
        ),
    ]
