# Generated by Django 4.2.23 on 2025-07-11 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingEventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ballot.member')),
                ('voting_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ballot.votingevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('voting_event', 'member')},
            },
        ),
    ]
